import AppKit

/// Reads and writes the system pasteboard. Change detection relies on
/// `changeCount`; our own writes advance the counter and are skipped so a
/// selection is not re-captured.
final class AppKitPasteboard: Whisk.Pasteboard {
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let board: NSPasteboard
    private var lastChangeCount: Int

    init(board: NSPasteboard = .general) {
        self.board = board
        lastChangeCount = board.changeCount
    }

    func readIfChanged() -> PasteboardSnapshot? {
        let count = board.changeCount
        guard count != lastChangeCount else { return nil }
        lastChangeCount = count
        guard !holdsConcealedContent(), let payload = readPayload() else { return nil }
        let app = NSWorkspace.shared.frontmostApplication
        var rtf: Data?
        if case .text = payload {
            rtf = board.data(forType: .rtf)
        }
        return PasteboardSnapshot(
            payload: payload,
            source: SourceApp(name: app?.localizedName, bundleID: app?.bundleIdentifier),
            rtf: rtf
        )
    }

    func write(_ payload: Payload, rtf: Data?) {
        board.clearContents()
        switch payload {
        case .text(let value):
            board.setString(value, forType: .string)
            if let rtf {
                board.setData(rtf, forType: .rtf)
            }
        case .link(let url):
            board.setString(url.absoluteString, forType: .string)
        case .image(let data):
            board.setData(data, forType: .png)
        case .fileReferences(let paths):
            board.writeObjects(paths.map { NSURL(fileURLWithPath: $0) })
        }
        lastChangeCount = board.changeCount
    }

    private func holdsConcealedContent() -> Bool {
        guard let types = board.types else { return false }
        return types.contains { Self.concealedTypes.contains($0.rawValue) }
    }

    private func readPayload() -> Payload? {
        if let urls = board.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return .fileReferences(urls.map(\.path))
        }
        if let png = imageData() {
            return .image(png)
        }
        if let string = board.string(forType: .string), !string.isEmpty {
            if let url = webLink(in: string) {
                return .link(url)
            }
            return .text(string)
        }
        return nil
    }

    private func imageData() -> Data? {
        if let png = board.data(forType: .png) {
            return png
        }
        if let tiff = board.data(forType: .tiff),
            let bitmap = NSBitmapImageRep(data: tiff),
            let png = bitmap.representation(using: .png, properties: [:])
        {
            return png
        }
        return nil
    }

    private func webLink(in string: String) -> URL? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty,
            trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
            let url = URL(string: trimmed),
            let scheme = url.scheme?.lowercased(),
            scheme == "http" || scheme == "https"
        else { return nil }
        return url
    }
}
